Pull request for HTML/CSS Project
GabrielJSuarez/PROJECT-BUILDING-WITH-BACKGROUNDS-AND-GRADIENTS pull request #2
Opened 2020-08-24 22:15 UTC by GabrielJSuarez

Pull request to merge page for the project Backgrounds And Gradients

2020-08-24 22:54 UTC, expjazz requested changes
Status: Changes Required :recycle: 

#### You did a great job on this page. It looks almost perfect. Just one small adjustment in the navbar:

- [ ] ![image](https://user-images.githubusercontent.com/61479648/91104102-764a4e80-e643-11ea-96d6-5af265094e50.png)

:arrow_up: 
You only have 8 (check the inline comments below for more detail).

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-24 22:54 UTC, expjazz commented on index.html
> +                    </div>
- [ ] There should be 8 items + the search bar. You missed the store.

- [ ] Also the layout of the first and last elements is different (they all have the same width). Kindly address that.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91103970-279cb480-e643-11ea-85fb-9a38cf09bcf2.png) |![image](https://user-images.githubusercontent.com/61479648/91103995-32efe000-e643-11ea-9c77-ea2d7015e597.png) |

2020-08-24 23:38 UTC, kitpao requested changes
# 👋 Hello @GabrielJSuarez 

You did nicely adding the missing store element, and besides that, you really did a great job with the rest of the elements 🏅 , you won't have major problems in the next projects 😉 . Now everything that remains is the size of your first and last elements. Kindly check below to see a hint ⬇️ 

### ♻️ Status: Your project requires 1 additional change ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-24 23:38 UTC, kitpao commented on style.css
> +}
- [ ] The first and last elements in your navbar are bigger than the rest, you can fix the issue just by giving a 'fixed' width to it. **Hint:** use rem units and see the difference :) 
Your navbar:
![image](https://user-images.githubusercontent.com/53256139/91106504-7729b300-e638-11ea-9d4d-364017a75bc6.png)

2020-08-25 01:12 UTC, kitpao approved these changes
# 👋 Hi again @GabrielJSuarez

Congratulations! Your page is completed and looks great 👏 

- [ ] **OPTIONAL** Now that everything is fine, you can update your screenshot so it displays your finished page 🌟 

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-25 01:56 UTC, merged